Container: Apply commit abf0796
ejabberdctl: Detect problem running etop and show some help

diff --git a/.github/container/ejabberdctl.template b/.github/container/ejabberdctl.template
--- a/.github/container/ejabberdctl.template
+++ b/.github/container/ejabberdctl.template
@@ -200,6 +200,21 @@ livewarning()
     fi
 }
 
+check_etop_result()
+{
+    result=$?
+    if [ $result -eq 1 ] ; then
+        echo ""
+        echo "It seems there was some problem running 'ejabberdctl etop'."
+        echo "Is the error message something like this?"
+        echo "  Failed to load module 'etop' because it cannot be found..."
+        echo "Then probably ejabberd was compiled with development tools disabled."
+        echo "To use 'etop', recompile ejabberd with: ./configure --enable-tools"
+        echo ""
+        exit $result
+    fi
+}
+
 help()
 {
     echo ""
@@ -371,6 +386,7 @@ case $1 in
                  -eval 'net_kernel:connect_node('"'$ERLANG_NODE'"')' \
                  -s etop \
                  -output text
+        check_etop_result
         ;;
     iexdebug)
         debugwarning
